[package]
name = "org2mdx"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "org2mdx"
path = "src/main.rs"

[lib]
name = "org2mdx"
path = "src/lib.rs"
crate-type = ["rlib"]

[dependencies]
napi = { version = "3", default-features = false, features = ["napi8"] }
napi-derive = "3"

[dev-dependencies]
serde_yaml = "0.9"
